#!/bin/bash -e
# The `makolr` script
# The Lightning Stalker, originally by Reza Toghraee
# https://stackoverflow.com/questions/14922960/is-there-an-easy-way-to-color-code-the-compiler-outputs

make ${@} 2>&1 | perl -wln -M'Term::ANSIColor' -e '
m/Building|gcc|g\+\+|\bCC\b|\bcc\b/ and print "\e[1;32m", "$_", "\e[0m"
or
m/Error/i and print "\e[1;91m", "$_", "\e[0m"
or
m/Warning/i and print "\e[1;93m", "$_", "\e[0m"
or
m/Linking|\.a\b/ and print "\e[1;36m", "$_", "\e[0m"
or
print; '
